### ISSUE TITLE
Rename Table of Contents

### ISSUE THREAD

**Issue by VennilaCity** [CityofOttawa/immigration_zen#6] opened 2013-09-20 17:36 UTC
a.  Can we rename it “On this page” “ Dans cette page”
b.  The title of the box disappears when we scroll can we make it stay?
c.  The table of contents colours should match the gateway the page is in. (different coulours)
d.      Table of content is pushed to the bottom of the page in IE

**Comment by minorOffense** [comment] 2013-09-30 18:36
1. For the title of the ToC that would be an enhancement to the code Dave wrote.
2. We _might_ be able to get the title to stick but we need to leave something behind for the list to anchor itself to upon returning
3. Colours are in the works in a separate issue.
4. That should be resolved with the Respond.js stuff but I'll double check.

For future reference, can you avoid stacking several issues into one post? Makes it hard to track what has/hasn't be done yet.

Thanks!

**Comment by minorOffense** [comment] 2013-09-30 18:38
Just tested ToC in IE, works just fine.

**Comment by minorOffense** [comment] 2013-09-30 18:41
See #15 about colour switching.

**Comment by VennilaCity** [comment] 2013-10-11 12:41
Any update?
@AaronByrne @DaveBagler

**Comment by minorOffense** [comment] 2013-10-11 15:00
## Nothing yet.

Mathew Winstone
mathew.winstone@ottawa.camailto:mathew.winstone@ottawa.ca

On 2013-10-11, at 8:41 AM, VennilaCity <notifications@github.com<mailto:notifications@github.com>>
 wrote:

Any update?
@AaronByrnehttps://github.com/AaronByrne @DaveBaglerhttps://github.com/DaveBagler

—
Reply to this email directly or view it on GitHubhttps://github.com/CityofOttawa/immigration_zen/issues/6#issuecomment-26133953.

This e-mail originates from the City of Ottawa e-mail system. Any 
distribution, use or copying of this e-mail or the information it 
contains by other than the intended recipient(s) is unauthorized. 
If you are not the intended recipient, please notify me at the 
telephone number shown above or by return e-mail and delete 
this communication and any copy immediately. Thank you.

Le présent courriel a été expédié par le système de courriels de 
la Ville d'Ottawa. Toute distribution, utilisation ou 
reproduction du courriel ou des renseignements qui s'y trouvent 
par une personne autre que son destinataire prévu est interdite. 
Si vous avez reçu le message par erreur, veuillez m'en aviser par 
téléphone (au numéro précité) ou par courriel, puis supprimer 
sans délai la version originale de la communication ainsi que 
toutes ses copies. Je vous remercie de votre collaboration.

**Closed as completed** 2016-08-24 20:52 UTC
Labels: enhancement
